$! BUILD.COM - build MariaDB for OpenVMS x86-64 with MMS and clang.
$!
$! Usage:  @[.VMS]BUILD <config> [target] [KEEP_GOING] [pcre2-root]
$!   config   a configuration generated by tools/prepare.sh, e.g. CLIENT;
$!            its MMS description is [.VMS.BUILD.<config>]DESCRIP.MMS
$!   target   MMS target (default ALL); CLEAN deletes [.VMSOBJ...]
$!
$! The description was generated on a host from MariaDB's CMake files
$! (tools/gen_mms.py): sources are compiled with VSI C++'s clang through
$! response files, objects go to [.VMSOBJ.<target>], libraries and images to
$! [.VMSOBJ].  Output ends with "BUILD: done" on success.
$ status = 44
$ on control_y then goto done
$ saved_default = f$environment("DEFAULT")
$ proc = f$environment("PROCEDURE")
$ set default 'f$parse(proc,,,"DEVICE")''f$parse(proc,,,"DIRECTORY")'
$ set default [-]
$ cfg = f$edit(p1, "UPCASE")
$ target = f$edit(p2, "UPCASE")
$ if target .eqs. "" then target = "ALL"
$! clang exits with warning severity when it warns, and MMS would stop on that:
$! carry on past warnings, stop on errors (KEEP_GOING: carry on past those too).
$ keep = "/IGNORE=WARNING"
$ if f$edit(p3, "UPCASE") .eqs. "KEEP_GOING" then keep = "/IGNORE=FATAL"
$! (the target may be a long list of LIB_ names: keep the message short)
$ write sys$output "BUILD: ''cfg' ''f$extract(0, 60, target)' in ''f$environment("DEFAULT")'"
$ if f$search("[.vms.build]''cfg'.dir") .eqs. ""
$ then
$   write sys$error "BUILD: no configuration ''cfg' (run tools/prepare.sh)"
$   goto done
$ endif
$! Objects of this configuration: [.VMSOBJ] for CLIENT, [.VMSOBJ_<config>] else
$! (tools/gen_mms.py).
$ objroot = "vmsobj"
$ if cfg .nes. "CLIENT" then objroot = "vmsobj_" + cfg
$ if target .eqs. "CLEAN"
$ then
$   if f$search("[.''objroot'...]*.*") .nes. "" then delete/nolog/exclude=*.dir [.'objroot'...]*.*;*
$   status = 1
$   goto finish
$ endif
$! clang reads its argv through the CRTL: keep case, and show diagnostics.
$ set process/parse_style=extended
$ define/process decc$argv_parse_style enable
$ define/process sys$error sys$output
$ clang :== $sys$system:clang.exe
$! <openssl/x.h> -> VSI SSL3's headers.
$ define/process openssl ssl3$include:
$! PCRE2$ROOT: the PCRE2 install tree (INCLUDE, LIB); build.sh passes it as P4.
$ if p4 .nes. "" then define/process/translation_attributes=concealed pcre2$root 'p4'
$! The server includes pcre2.h from there: say so now, not at item_cmpfunc.cc.
$ if cfg .eqs. "SERVER" .and. f$search("pcre2$root:[include]pcre2.h") .eqs. ""
$ then
$   write sys$error "BUILD: no PCRE2$ROOT:[INCLUDE]PCRE2.H; PCRE2$ROOT must be the rooted"
$   write sys$error "BUILD: clang install tree of vms-pcre2, dev:[dir.INSTALL_X86_64_CLANG.]"
$   write sys$error "BUILD: (P4, or the 8th column of tools/nodes.conf for build.sh)"
$   goto done
$ endif

$ @[.vms.build.'cfg']mkdirs.com
$! clang finds a response file only by an absolute UNIX path, not by a
$! relative one with directories in it: pass the tree's path to MMS as ROOT.
$ dflt = f$environment("DEFAULT")
$ root = "/" + (f$parse(dflt,,,"DEVICE") - ":")
$ dirs = f$parse(dflt,,,"DIRECTORY") - "[" - "]" - "<" - ">"
$ i = 0
$dirloop:
$ e = f$element(i, ".", dirs)
$ if e .eqs. "." .or. e .eqs. "" then goto dirdone
$ root = root + "/" + e
$ i = i + 1
$ goto dirloop
$dirdone:
$ mms/description=[.vms.build.'cfg']descrip.mms/macro=("ROOT=''root'")'keep' 'target'
$ status = $status
$finish:
$ if status then write sys$output "BUILD: done"
$done:
$ set default 'saved_default'
$ exit status
