$! BUILD.COM - build MariaDB for OpenVMS x86-64 with MMS and clang.
$!
$! Usage:  @[.VMS]BUILD <config> [target] [KEEP_GOING] [pcre2-root]
$!   config   a configuration generated by tools/prepare.sh, e.g. CLIENT;
$!            its MMS description is [.VMS.BUILD.<config>]DESCRIP.MMS
$!   target   MMS target (default ALL); CLEAN deletes [.VMSOBJ...]
$!
$! The description was generated on a host from MariaDB's CMake files
$! (tools/gen_mms.py): sources are compiled with VSI C++'s clang through
$! response files, objects go to [.VMSOBJ.<target>], libraries and images to
$! [.VMSOBJ].  Output ends with "BUILD: done" on success.
$ status = 44
$ on control_y then goto done
$ saved_default = f$environment("DEFAULT")
$ proc = f$environment("PROCEDURE")
$ set default 'f$parse(proc,,,"DEVICE")''f$parse(proc,,,"DIRECTORY")'
$ set default [-]
$ cfg = f$edit(p1, "UPCASE")
$ target = f$edit(p2, "UPCASE")
$ if target .eqs. "" then target = "ALL"
$! clang exits with warning severity when it warns, and MMS would stop on that:
$! carry on past warnings, stop on errors (KEEP_GOING: carry on past those too).
$ keep = "/IGNORE=WARNING"
$ if f$edit(p3, "UPCASE") .eqs. "KEEP_GOING" then keep = "/IGNORE=FATAL"
$! (the target may be a long list of LIB_ names: keep the message short)
$ write sys$output "BUILD: ''cfg' ''f$extract(0, 60, target)' in ''f$environment("DEFAULT")'"
$ if f$search("[.vms.build]''cfg'.dir") .eqs. ""
$ then
$   write sys$error "BUILD: no configuration ''cfg' (run tools/prepare.sh)"
$   goto done
$ endif
$! Objects of this configuration: [.VMSOBJ] for CLIENT, [.VMSOBJ_<config>] else
$! (tools/gen_mms.py).
$ objroot = "vmsobj"
$ if cfg .nes. "CLIENT" then objroot = "vmsobj_" + cfg
$ if target .eqs. "CLEAN"
$ then
$   if f$search("[.''objroot'...]*.*") .nes. "" then delete/nolog/exclude=*.dir [.'objroot'...]*.*;*
$   status = 1
$   goto finish
$ endif
$! clang reads its argv through the CRTL: keep case, and show diagnostics.
$ set process/parse_style=extended
$ define/process decc$argv_parse_style enable
$ define/process sys$error sys$output
$ clang :== $sys$system:clang.exe
$! <openssl/x.h> -> VSI SSL3's headers.
$ define/process openssl ssl3$include:
$! PCRE2$ROOT: the PCRE2 install tree (INCLUDE, LIB); build.sh passes it as P4.
$ if p4 .nes. "" then define/process/translation_attributes=concealed pcre2$root 'p4'
$! The server includes pcre2.h from there: say so now, not at item_cmpfunc.cc.
$ if cfg .eqs. "SERVER" .and. f$search("pcre2$root:[include]pcre2.h") .eqs. ""
$ then
$   write sys$error "BUILD: no PCRE2$ROOT:[INCLUDE]PCRE2.H; PCRE2$ROOT must be the rooted"
$   write sys$error "BUILD: clang install tree of vms-pcre2, dev:[dir.INSTALL_X86_64_CLANG.]"
$   write sys$error "BUILD: (P4, or the 8th column of tools/nodes.conf for build.sh)"
$   goto done
$ endif
$! ...and it must be the clang (LP64) build: vms-pcre2's VSI C (ILP32) tree has
$! the same layout and links, but its pointers and longs are half the size.
$! Objects from clang carry "clang version" (in no VSI C object).
$ if cfg .eqs. "SERVER"
$ then
$   define/user sys$output nla0:
$   define/user sys$error nla0:
$   search pcre2$root:[lib]pcre2-8.olb "clang version"
$   if $severity .ne. 1
$   then
$     write sys$error "BUILD: PCRE2$ROOT:[LIB]PCRE2-8.OLB was not built by clang: PCRE2$ROOT must"
$     write sys$error "BUILD: be vms-pcre2's clang tree, dev:[dir.INSTALL_X86_64_CLANG.], not"
$     write sys$error "BUILD: INSTALL_X86_64 (VSI C, ILP32; docs/DECISIONS.md D11)"
$     goto done
$   endif
$ endif
$! The images must take PCRE2 from that same library: an options file edited
$! to name another (e.g. [INSTALL_X86_64.LIB], the VSI C build) would get past
$! the check above, link, and fail at run time.
$ if cfg .nes. "SERVER" then goto optdone
$ nbad = 0
$optfile:
$ opt = f$search("[.vms.build.''cfg']*.opt")
$ if opt .eqs. "" then goto optend
$ open/read optf 'opt'
$optline:
$ read/end=optclose optf line
$ u = f$edit(line, "UPCASE,TRIM")
$ if f$locate("PCRE2", u) .eq. f$length(u) then goto optline
$ if u .eqs. "PCRE2$ROOT:[LIB]PCRE2-8.OLB/LIBRARY" then goto optline
$ write sys$error "BUILD: ''f$edit(f$parse(opt,,,"NAME"), "UPCASE")'.OPT: ''line'"
$ nbad = nbad + 1
$ goto optline
$optclose:
$ close optf
$ goto optfile
$optend:
$ if nbad .eq. 0 then goto optdone
$ write sys$error "BUILD: the options files above must name PCRE2 only as"
$ write sys$error "BUILD: PCRE2$ROOT:[LIB]PCRE2-8.OLB/library (the clang tree in P4): don't edit"
$ write sys$error "BUILD: [.VMS.BUILD.SERVER]*.OPT; regenerate them with tools/prepare.sh"
$ goto done
$optdone:

$ @[.vms.build.'cfg']mkdirs.com
$! clang finds a response file only by an absolute UNIX path, not by a
$! relative one with directories in it: pass the tree's path to MMS as ROOT.
$ dflt = f$environment("DEFAULT")
$ root = "/" + (f$parse(dflt,,,"DEVICE") - ":")
$ dirs = f$parse(dflt,,,"DIRECTORY") - "[" - "]" - "<" - ">"
$ i = 0
$dirloop:
$ e = f$element(i, ".", dirs)
$ if e .eqs. "." .or. e .eqs. "" then goto dirdone
$ root = root + "/" + e
$ i = i + 1
$ goto dirloop
$dirdone:
$! Compiler self-check (vms/tests/calloc_shape_test.c): with the build's own
$! flags, as C and as C++, a calloc-style helper must return its own block
$! (VSI clang's memset/bzero miscompile; clang_common.rsp).
$ rsp = root + "/vms/build/" + f$edit(cfg, "LOWERCASE") + "/vms_crtl_init.rsp"
$! One output file per run: two DEFINE/USERs of one name make two versions,
$! and only the newer would be read.
$ set noon
$ npass = 0
$ chk = ""
$ lang = "C"
$ckrun:
$ obj = objroot + "/calloc_shape_" + lang
$ vobj = "[." + objroot + "]calloc_shape_" + lang
$ out = "sys$scratch:calloc_shape_''lang'.out"
$ if f$search(out) .nes. "" then delete/nolog 'out';*
$ opts = ""
$ if lang .eqs. "CXX" then opts = """-x"" ""c++"" ""-std=gnu++11"""
$ clang "@''rsp'" 'opts' -c vms/tests/calloc_shape_test.c -o 'obj'.obj
$ link/exe='vobj'.exe 'vobj'.obj
$ define/user sys$output 'out'
$ run 'vobj'.exe
$ chk = chk + "," + out
$ if f$search(out) .eqs. "" then goto cknext
$ open/read ck 'out'
$ckloop:
$ read/end=ckend ck line
$ if line .eqs. "CALLOC_SHAPE: PASS" then npass = npass + 1
$ goto ckloop
$ckend:
$ close ck
$cknext:
$ if lang .eqs. "C"
$ then
$   lang = "CXX"
$   goto ckrun
$ endif
$ set on
$ if npass .ne. 2
$ then
$   type 'f$extract(1, 999, chk)'
$   write sys$error "BUILD: compiler self-check failed: a memset/bzero calloc shape returned"
$   write sys$error "BUILD: the wrong pointer (vms/tests/calloc_shape_test.c; see"
$   write sys$error "BUILD: -fno-builtin-memset/-bzero in vms/config/clang_common.rsp)"
$   goto done
$ endif
$ write sys$output "BUILD: compiler self-check passed (memset/bzero calloc shape, C and C++)"
$! Format-attribute check (vms/tests/format_attr_test.c): MariaDB's
$! ATTRIBUTE_FORMAT(printf, ...) must survive vms_lp64.h's printf macro (patch
$! 0029), or clang drops it with a warning on every file and checks no formats.
$ set noon
$ clang "@''rsp'" "-Werror=ignored-attributes" "-Werror=format" -I include -
        -c vms/tests/format_attr_test.c -o 'objroot'/format_attr.obj
$ fstatus = $status
$ set on
$ if .not. fstatus
$ then
$   write sys$error "BUILD: format-attribute check failed: ATTRIBUTE_FORMAT(printf, ...) reaches"
$   write sys$error "BUILD: clang as format(vms_lp64_printf, ...) (patch 0029, include/my_attribute.h)"
$   goto done
$ endif
$ write sys$output "BUILD: format-attribute check passed (printf formats are checked)"
$ mms/description=[.vms.build.'cfg']descrip.mms/macro=("ROOT=''root'")'keep' 'target'
$ status = $status
$finish:
$ if status then write sys$output "BUILD: done"
$done:
$ set default 'saved_default'
$ exit status
