#!/usr/bin/env python3
"""gen_mms.py <config> - generate the MMS build for one configuration.

Reads the CMake File API reply of cache/cmake-<config>/ (the host-side
cross-configure) and overlay/vms/config/<config>.targets (which targets to
build), and writes into staging/<name>/vms/build/<config>/:

  DESCRIP.MMS        one rule per object, library and image
  <target>_<n>.rsp   clang response file per compile group (defines, include
                     paths, language standard) - keeps DCL lines short
  <image>.opt        linker options file per executable

Paths: the VMS build runs with the default directory at the top of the
source tree, so source paths are used as they are, generated files from the
host build directory live under vmsgen/ (copied there by prepare.sh), and
objects, libraries and images go under vmsobj/.  Only -D and -std are taken
from CMake's compile flags (the rest are GCC's); our own clang flags come from
overlay/vms/config/clang_common.rsp.
"""
import glob
import json
import os
import re
import sys

TOP = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def conf():
    vals = {}
    for line in open(os.path.join(TOP, 'upstream.conf')):
        m = re.match(r'(\w+)=(.*)', line.strip())
        if m:
            vals[m.group(1)] = m.group(2).strip('"')
    return vals


def vms_dir(unix_dir):
    """strings/x -> [.strings.x]"""
    parts = [p for p in unix_dir.split('/') if p and p != '.']
    return '[.' + '.'.join(parts) + ']' if parts else '[]'


def vms_file(unix_path):
    d, f = os.path.split(unix_path)
    return vms_dir(d) + f


def deps_line(target, deps):
    """MMS dependency line, continued with '-' so no line gets long."""
    if not deps:
        return target + ' :'
    return target + ' : ' + ', -\n    '.join(deps)


def main():
    cfg = sys.argv[1]
    up = conf()
    name = '%s-%s' % (up['UPSTREAM_NAME'], up['UPSTREAM_VERSION'])
    stage = os.path.join(TOP, 'staging', name)
    bdir = os.path.join(TOP, 'cache', 'cmake-' + cfg)
    sysroot = os.path.join(TOP, 'cache', 'vms-sysroot')
    out = os.path.join(stage, 'vms', 'build', cfg)
    os.makedirs(out, exist_ok=True)
    wanted = [l.split('#')[0].strip() for l in
              open(os.path.join(TOP, 'overlay', 'vms', 'config', cfg + '.targets'))]
    wanted = [w for w in wanted if w]
    common = open(os.path.join(TOP, 'overlay', 'vms', 'config', 'clang_common.rsp')).read()
    common = '\n'.join(l for l in common.splitlines() if l.strip() and not l.startswith('#'))

    reply = os.path.join(bdir, '.cmake', 'api', 'v1', 'reply')
    index = json.load(open(sorted(glob.glob(os.path.join(reply, 'index-*.json')))[-1]))
    cm = [o for o in index['objects'] if o['kind'] == 'codemodel'][0]
    model = json.load(open(os.path.join(reply, cm['jsonFile'])))
    targets = {}
    for t in model['configurations'][0]['targets']:
        tj = json.load(open(os.path.join(reply, t['jsonFile'])))
        targets[tj['name']] = tj
    # archive file name (libstrings.a) -> target name
    by_archive = {}
    for n, tj in targets.items():
        for a in tj.get('artifacts', []):
            by_archive[os.path.basename(a['path'])] = n

    def map_path(p):
        if p.startswith(stage + '/') or p == stage:
            return os.path.relpath(p, stage)
        if p.startswith(bdir + '/') or p == bdir:
            return os.path.join('vmsgen', os.path.relpath(p, bdir))
        if p.startswith(sysroot):
            return None          # VSI SSL3 headers: OPENSSL logical on VMS
        sys.exit('gen_mms: path outside the tree: %s' % p)

    mms = ['! DESCRIP.MMS for MariaDB %s, configuration "%s", generated by tools/gen_mms.py.'
           % (up['UPSTREAM_VERSION'], cfg),
           '! Run from the top of the source tree: MMS/DESCRIPTION=[.VMS.BUILD.%s]DESCRIP.MMS'
           % cfg.upper(),
           '! (see vms/build.com).  Do not edit; regenerate with tools/prepare.sh.', '',
           'CLANG = clang',
           '! ROOT: the tree as an absolute UNIX path, set by vms/build.com (clang',
           '! does not find a response file by a relative path with directories).',
           'ROOT = .', '']
    rspdir = 'vms/build/%s' % cfg
    all_outputs = []
    obj_of_target = {}
    pushdirs = {'vms', 'vmsgen'}

    for tname in wanted:
        if tname not in targets:
            sys.exit('gen_mms: no target %s in %s' % (tname, bdir))
        tj = targets[tname]
        objs = []
        used_names = set()
        for gi, g in enumerate(tj.get('compileGroups', [])):
            flags = []
            for frag in g.get('compileCommandFragments', []):
                for f in frag['fragment'].split():
                    if f.startswith('-std='):
                        flags.append(f)
                    elif f.startswith('-D') and not f.startswith('-D_FORTIFY_SOURCE'):
                        flags.append(f)
            for d in g.get('defines', []):
                flags.append('-D' + d['define'])
            for inc in g.get('includes', []):
                m = map_path(inc['path'])
                if m is not None:
                    flags.append('-I' + m)
                    pushdirs.add(m.split('/')[0])
            rsp = '%s_%d.rsp' % (tname, gi)
            with open(os.path.join(out, rsp), 'w') as f:
                f.write(common + '\n' + '\n'.join(dict.fromkeys(flags)) + '\n')
            for si in g['sourceIndexes']:
                src = tj['sources'][si]['path']
                if os.path.isabs(src):
                    src = map_path(src)
                pushdirs.add(src.split('/')[0])
                base = os.path.splitext(os.path.basename(src))[0]
                oname = base
                k = 1
                while oname.lower() in used_names:
                    k += 1
                    oname = '%s_%d' % (base, k)
                used_names.add(oname.lower())
                obj = 'vmsobj/%s/%s.obj' % (tname, oname)
                objs.append(obj)
                mms.append('%s : %s' % (vms_file(obj), vms_file(src)))
                mms.append('\t$(CLANG) @$(ROOT)/%s/%s -c %s -o %s' % (rspdir, rsp, src, obj))
        # Objects of OBJECT_LIBRARY targets used by this one ($<TARGET_OBJECTS>).
        for s in tj.get('sources', []):
            m = re.search(r'CMakeFiles/([^/]+)\.dir/', s['path'])
            if s['path'].endswith('.o') and m and m.group(1) in obj_of_target:
                for o in obj_of_target[m.group(1)]:
                    if o not in objs:
                        objs.append(o)
        obj_of_target[tname] = objs
        mms.append('')
        if tj['type'] in ('STATIC_LIBRARY', 'OBJECT_LIBRARY', 'MODULE_LIBRARY', 'SHARED_LIBRARY'):
            olb = 'vmsobj/%s.olb' % tname
            all_outputs.append(olb)
            mms.append(deps_line(vms_file(olb), [vms_file(o) for o in objs]))
            mms.append('\tif f$search("%s") .eqs. "" then library/create/object %s' %
                       (vms_file(olb), vms_file(olb)))
            dirs = sorted({os.path.dirname(o) for o in objs})
            for d in dirs:
                mms.append('\tlibrary/replace %s %s*.obj' % (vms_file(olb), vms_dir(d)))
        elif tj['type'] == 'EXECUTABLE':
            exe = 'vmsobj/%s.exe' % tname
            opt = '%s.opt' % tname
            libs = []
            for frag in tj.get('link', {}).get('commandFragments', []):
                if frag.get('role') == 'libraries' and frag['fragment'].endswith('.a'):
                    lt = by_archive.get(os.path.basename(frag['fragment']))
                    if lt:
                        libs.append(lt)
            missing = [l for l in libs if l not in wanted]
            if missing:
                sys.exit('gen_mms: %s links %s, not in %s.targets' % (tname, missing, cfg))
            with open(os.path.join(out, opt), 'w') as f:
                # The linker takes no wildcards in an options file.
                for o in objs:
                    f.write('%s\n' % vms_file(o))
                for l in libs:
                    f.write('%s%s.olb/library\n' % (vms_dir('vmsobj'), l))
                f.write('sys$share:ssl3$libssl_shr/share\nsys$share:ssl3$libcrypto_shr/share\n')
            all_outputs.append(exe)
            deps = [vms_file(o) for o in objs] + ['%s%s.olb' % (vms_dir('vmsobj'), l)
                                                 for l in dict.fromkeys(libs)]
            mms.append(deps_line(vms_file(exe), deps))
            mms.append('\tlink/exe=%s/map=%s/traceback %s/options' %
                       (vms_file(exe), vms_file('vmsobj/%s.map' % tname),
                        vms_file('%s/%s' % (rspdir, opt))))
        mms.append('')

    mms.insert(5, deps_line('ALL', [vms_file(o) for o in all_outputs]))
    mms.insert(6, '\t! built')
    mms.insert(7, '')
    with open(os.path.join(out, 'PUSHDIRS.TXT'), 'w') as f:
        f.write('\n'.join(sorted(pushdirs)) + '\n')
    # clang -o does not create directories: vms/build.com runs this first.
    with open(os.path.join(out, 'MKDIRS.COM'), 'w') as f:
        f.write('$! Create the object directories for configuration %s (generated).\n' % cfg)
        dirs = sorted({'vmsobj'} | {os.path.dirname(o) for v in obj_of_target.values() for o in v})
        for d in dirs:
            f.write('$ if f$search("%s") .eqs. "" then create/directory %s\n' %
                    (vms_dir(os.path.dirname(d)) + os.path.basename(d) + ".DIR",
                     vms_dir(d)))
    with open(os.path.join(out, 'DESCRIP.MMS'), 'w') as f:
        f.write('\n'.join(mms) + '\n')
    print('gen_mms: %s: %d targets, %d objects -> %s' %
          (cfg, len(wanted), sum(len(v) for v in obj_of_target.values()),
           os.path.relpath(out, TOP)))


if __name__ == '__main__':
    main()
