#!/usr/bin/env python3
"""gen_mms.py <config> - generate the MMS build for one configuration.

Reads the CMake File API reply of cache/cmake-<config>/ (the host-side
cross-configure) and overlay/vms/config/<config>.targets (which targets to
build), and writes into staging/<name>/vms/build/<config>/:

  DESCRIP.MMS        one rule per object, library and image
  <target>_<n>.rsp   clang response file per compile group (defines, include
                     paths, language standard) - keeps DCL lines short
  <image>.opt        linker options file per executable

Paths: the VMS build runs with the default directory at the top of the
source tree, so source paths are used as they are, generated files from the
host build directory live under vmsgen/ (copied there by prepare.sh), and
objects, libraries and images go under vmsobj/.  Only -D and -std are taken
from CMake's compile flags (the rest are GCC's); our own clang flags come from
overlay/vms/config/clang_common.rsp.
"""
import glob
import json
import os
import re
import sys

TOP = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def conf():
    vals = {}
    for line in open(os.path.join(TOP, 'upstream.conf')):
        m = re.match(r'(\w+)=(.*)', line.strip())
        if m:
            vals[m.group(1)] = m.group(2).strip('"')
    return vals


def vms_dir(unix_dir):
    """strings/x -> [.strings.x]"""
    parts = [p for p in unix_dir.split('/') if p and p != '.']
    return '[.' + '.'.join(parts) + ']' if parts else '[]'


def vms_file(unix_path):
    d, f = os.path.split(unix_path)
    return vms_dir(d) + f


def deps_line(target, deps):
    """MMS dependency line, continued with '-' so no line gets long."""
    if not deps:
        return target + ' :'
    return target + ' : ' + ', -\n    '.join(deps)


def main():
    cfg = sys.argv[1]
    up = conf()
    name = '%s-%s' % (up['UPSTREAM_NAME'], up['UPSTREAM_VERSION'])
    stage = os.path.join(TOP, 'staging', name)
    bdir = os.path.join(TOP, 'cache', 'cmake-' + cfg)
    sysroot = os.path.join(TOP, 'cache', 'vms-sysroot')
    out = os.path.join(stage, 'vms', 'build', cfg)
    os.makedirs(out, exist_ok=True)
    wanted = [l.split('#')[0].strip() for l in
              open(os.path.join(TOP, 'overlay', 'vms', 'config', cfg + '.targets'))]
    wanted = [w for w in wanted if w]
    # Extra linker input for every image of the configuration (libraries CMake
    # does not build, e.g. PCRE2), one options-file line each.
    extra_link = os.path.join(TOP, 'overlay', 'vms', 'config', cfg + '.link')
    common = open(os.path.join(TOP, 'overlay', 'vms', 'config', 'clang_common.rsp')).read()
    common = '\n'.join(l for l in common.splitlines() if l.strip() and not l.startswith('#'))

    reply = os.path.join(bdir, '.cmake', 'api', 'v1', 'reply')
    index = json.load(open(sorted(glob.glob(os.path.join(reply, 'index-*.json')))[-1]))
    cm = [o for o in index['objects'] if o['kind'] == 'codemodel'][0]
    model = json.load(open(os.path.join(reply, cm['jsonFile'])))
    targets = {}
    for t in model['configurations'][0]['targets']:
        tj = json.load(open(os.path.join(reply, t['jsonFile'])))
        targets[tj['name']] = tj
    # archive file name (libstrings.a) -> target name
    by_archive = {}
    for n, tj in targets.items():
        for a in tj.get('artifacts', []):
            by_archive[os.path.basename(a['path'])] = n

    def map_path(p):
        if p.startswith(stage + '/') or p == stage:
            return os.path.relpath(p, stage)
        if p.startswith(bdir + '/') or p == bdir:
            return os.path.join('vmsgen', os.path.relpath(p, bdir))
        if p.startswith(sysroot):
            # Host copies of VMS headers (tools/sysroot.sh) -> where they are
            # on the node: OpenSSL through the OPENSSL logical (no -I needed),
            # PCRE2 in the install tree vms/build.com defines as PCRE2$ROOT.
            if p.rstrip('/').endswith('/include/pcre2'):
                return '/PCRE2$ROOT/INCLUDE'
            return None
        sys.exit('gen_mms: path outside the tree: %s' % p)

    mms = ['! DESCRIP.MMS for MariaDB %s, configuration "%s", generated by tools/gen_mms.py.'
           % (up['UPSTREAM_VERSION'], cfg),
           '! Run from the top of the source tree: MMS/DESCRIPTION=[.VMS.BUILD.%s]DESCRIP.MMS'
           % cfg.upper(),
           '! (see vms/build.com).  Do not edit; regenerate with tools/prepare.sh.', '',
           'CLANG = clang',
           '! ROOT: the tree as an absolute UNIX path, set by vms/build.com (clang',
           '! does not find a response file by a relative path with directories).',
           'ROOT = .', '']
    rspdir = 'vms/build/%s' % cfg
    # Objects, libraries and images: [.VMSOBJ] for the client configuration
    # (Stage A, the tests use it), [.VMSOBJ_<config>] for any other.
    objroot = 'vmsobj' if cfg == 'client' else 'vmsobj_' + cfg
    all_outputs = []
    obj_of_target = {}
    weight_of_target = {}       # compile cost estimate: C++ 3, C 1 per object
    pushdirs = {'vms', 'vmsgen'}

    # vms/vms_crtl_init.c: C RTL features, linked into every image.
    init_obj = '%s/vms_crtl_init.obj' % objroot
    with open(os.path.join(out, 'vms_crtl_init.rsp'), 'w') as f:
        f.write(common + '\n-std=gnu99\n')
    mms.append('%s : %s' % (vms_file(init_obj), vms_file('vms/vms_crtl_init.c')))
    mms.append('\t$(CLANG) @$(ROOT)/%s/vms_crtl_init.rsp -c vms/vms_crtl_init.c -o %s'
               % (rspdir, init_obj))
    mms.append('')

    for tname in wanted:
        if tname not in targets:
            sys.exit('gen_mms: no target %s in %s' % (tname, bdir))
        tj = targets[tname]
        objs = []
        used_names = set()
        weight = 0
        for gi, g in enumerate(tj.get('compileGroups', [])):
            flags = []
            for frag in g.get('compileCommandFragments', []):
                for f in frag['fragment'].split():
                    if f.startswith('-std='):
                        flags.append(f)
                    elif f.startswith('-D') and not f.startswith('-D_FORTIFY_SOURCE'):
                        flags.append(f)
            for d in g.get('defines', []):
                flags.append('-D' + d['define'])
            for inc in g.get('includes', []):
                m = map_path(inc['path'])
                if m is not None:
                    flags.append('-I' + m)
                    if not m.startswith('/'):
                        pushdirs.add(m.split('/')[0])
            rsp = '%s_%d.rsp' % (tname, gi)
            with open(os.path.join(out, rsp), 'w') as f:
                f.write(common + '\n' + '\n'.join(dict.fromkeys(flags)) + '\n')
            weight += (3 if g['language'] == 'CXX' else 1) * len(g['sourceIndexes'])
            for si in g['sourceIndexes']:
                src = tj['sources'][si]['path']
                if os.path.isabs(src):
                    src = map_path(src)
                pushdirs.add(src.split('/')[0])
                base = os.path.splitext(os.path.basename(src))[0]
                oname = base
                k = 1
                while oname.lower() in used_names:
                    k += 1
                    oname = '%s_%d' % (base, k)
                used_names.add(oname.lower())
                obj = '%s/%s/%s.obj' % (objroot, tname, oname)
                objs.append(obj)
                mms.append('%s : %s' % (vms_file(obj), vms_file(src)))
                mms.append('\t$(CLANG) @$(ROOT)/%s/%s -c %s -o %s' % (rspdir, rsp, src, obj))
        # Objects of OBJECT_LIBRARY targets used by this one ($<TARGET_OBJECTS>).
        for s in tj.get('sources', []):
            m = re.search(r'CMakeFiles/([^/]+)\.dir/', s['path'])
            if s['path'].endswith('.o') and m and m.group(1) in obj_of_target:
                for o in obj_of_target[m.group(1)]:
                    if o not in objs:
                        objs.append(o)
        obj_of_target[tname] = objs
        weight_of_target[tname] = weight
        mms.append('')
        if tj['type'] in ('STATIC_LIBRARY', 'OBJECT_LIBRARY', 'MODULE_LIBRARY', 'SHARED_LIBRARY'):
            olb = '%s/%s.olb' % (objroot, tname)
            all_outputs.append(olb)
            # A short pseudo-target per library, for parallel builds: file
            # specs as MMS targets are long and must match the rule's case.
            mms.append('LIB_%s : %s' % (re.sub(r'\W', '_', tname).upper(), vms_file(olb)))
            mms.append('\t! %s up to date' % tname)
            mms.append('')
            mms.append(deps_line(vms_file(olb), [vms_file(o) for o in objs]))
            mms.append('\tif f$search("%s") .eqs. "" then library/create/object %s' %
                       (vms_file(olb), vms_file(olb)))
            dirs = sorted({os.path.dirname(o) for o in objs})
            for d in dirs:
                mms.append('\tlibrary/replace %s %s*.obj' % (vms_file(olb), vms_dir(d)))
        elif tj['type'] == 'EXECUTABLE':
            exe = '%s/%s.exe' % (objroot, tname)
            opt = '%s.opt' % tname
            libs = []
            for frag in tj.get('link', {}).get('commandFragments', []):
                if frag.get('role') == 'libraries' and frag['fragment'].endswith('.a'):
                    lt = by_archive.get(os.path.basename(frag['fragment']))
                    if lt:
                        libs.append(lt)
            missing = [l for l in libs if l not in wanted]
            if missing:
                sys.exit('gen_mms: %s links %s, not in %s.targets' % (tname, missing, cfg))
            with open(os.path.join(out, opt), 'w') as f:
                # The linker takes no wildcards in an options file.
                for o in objs:
                    f.write('%s\n' % vms_file(o))
                f.write('%s\n' % vms_file(init_obj))
                # clang marks the section writable; give it the system's
                # LIB$INITIALIZE attributes (see vms/vms_crtl_init.c).
                f.write('PSECT_ATTR=LIB$INITIALIZE,CON,REL,GBL,NOSHR,NOEXE,RD,NOWRT\n')
                for l in libs:
                    f.write('%s%s.olb/library\n' % (vms_dir(objroot), l))
                if os.path.exists(extra_link):
                    for l in open(extra_link):
                        if l.strip() and not l.startswith('#'):
                            f.write(l.strip() + '\n')
                f.write('sys$share:ssl3$libssl_shr/share\nsys$share:ssl3$libcrypto_shr/share\n')
            all_outputs.append(exe)
            deps = [vms_file(o) for o in objs] + [vms_file(init_obj)] + ['%s%s.olb' % (vms_dir(objroot), l)
                                                 for l in dict.fromkeys(libs)]
            mms.append(deps_line(vms_file(exe), deps))
            # /THREADS_ENABLE: kernel threads and upcalls.  Without it all
            # POSIX threads share one kernel thread, and a blocking system
            # call (mariadbd's poll() on its listening sockets) stops them
            # all: connections were accepted but never answered.
            mms.append('\tlink/exe=%s/map=%s/traceback/threads_enable %s/options' %
                       (vms_file(exe), vms_file('%s/%s.map' % (objroot, tname)),
                        vms_file('%s/%s' % (rspdir, opt))))
        mms.append('')

    mms.insert(5, deps_line('ALL', [vms_file(o) for o in all_outputs]))
    mms.insert(6, '\t! built')
    mms.insert(7, '')
    # Library targets and their compile cost (C++ objects count 3, C 1), for parallel builds
    # (build.sh JOBS=n splits them into n MMS runs; images link afterwards).
    with open(os.path.join(out, 'TARGETS.TXT'), 'w') as f:
        for tname in wanted:
            if targets[tname]['type'] != 'EXECUTABLE':
                f.write('LIB_%s %d\n' % (re.sub(r'\W', '_', tname).upper(),
                                        weight_of_target[tname]))
    # Directories needed but invisible to CMake's description (sources
    # #include'd by relative path, e.g. ../libmysqld/embedded_priv.h).
    extra_dirs = os.path.join(TOP, 'overlay', 'vms', 'config', cfg + '.pushdirs')
    if os.path.exists(extra_dirs):
        for l in open(extra_dirs):
            if l.strip() and not l.startswith('#'):
                pushdirs.add(l.strip())
    with open(os.path.join(out, 'PUSHDIRS.TXT'), 'w') as f:
        f.write('\n'.join(sorted(pushdirs)) + '\n')
    # clang -o does not create directories: vms/build.com runs this first.
    with open(os.path.join(out, 'MKDIRS.COM'), 'w') as f:
        f.write('$! Create the object directories for configuration %s (generated).\n' % cfg)
        dirs = sorted({objroot} | {os.path.dirname(o) for v in obj_of_target.values() for o in v})
        for d in dirs:
            f.write('$ if f$search("%s") .eqs. "" then create/directory %s\n' %
                    (vms_dir(os.path.dirname(d)) + os.path.basename(d) + ".DIR",
                     vms_dir(d)))
    with open(os.path.join(out, 'DESCRIP.MMS'), 'w') as f:
        f.write('\n'.join(mms) + '\n')
    print('gen_mms: %s: %d targets, %d objects -> %s' %
          (cfg, len(wanted), sum(len(v) for v in obj_of_target.values()),
           os.path.relpath(out, TOP)))


if __name__ == '__main__':
    main()
