#!/usr/bin/env python3
"""replay_answers.py <answers.txt> <policy.txt> <results.txt> <manifest.txt>

Merge one replay run into overlay/vms/config/answers.txt and regenerate
overlay/cmake/os/OpenVMSCache.cmake from it and overlay/vms/config/manual.txt.

answers.txt: "VAR VALUE  # source", one per CMake cache variable, sorted; VALUE
is 1, "" (no) or a number/string.  manual.txt has the same form plus comments
and always wins: it holds answers a replay cannot get right (see its header).
"""
import os
import re
import sys

TOP = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANUAL = os.path.join(TOP, 'overlay', 'vms', 'config', 'manual.txt')
CACHE = os.path.join(TOP, 'overlay', 'cmake', 'os', 'OpenVMSCache.cmake')


def read_answers(path):
    out = {}
    if os.path.exists(path):
        for line in open(path):
            line = line.rstrip('\n')
            if not line.strip() or line.startswith('#'):
                continue
            m = re.match(r'(\S+)\s+("[^"]*"|\S+)\s*(#\s*(.*))?$', line)
            if not m:
                sys.exit('replay_answers: bad line in %s: %s' % (path, line))
            out[m.group(1)] = (m.group(2), (m.group(4) or '').strip())
    return out


def main():
    answers_path, policy, results, manifest = sys.argv[1:5]
    answers = read_answers(answers_path)
    for line in open(policy):
        var, val, why = line.rstrip('\n').split(' ', 2)
        answers[var] = (val, 'policy: ' + why)
    meta = {}
    for line in open(manifest):
        f = line.split()
        if f:
            meta[f[0]] = f
    added = 0
    for line in open(results):
        m = re.match(r'RESULT (\d+) (\S+) cc=(\S*) link=(\S*) out=(.*?) msg=', line)
        if not m:
            continue
        tag, var, cc, link, out = m.groups()
        _, _, mod, kind, lang, runvar, checkvar = meta[tag]
        ok = link == '1'
        src = 'replay %s %s' % (mod, lang)
        if kind == 'S':
            sz = re.search(r'INFO:size\[0*(\d+)\]', out)
            answers[var] = ('1' if ok and sz else '""', src)
            answers[var[len('HAVE_'):]] = (sz.group(1) if ok and sz else '""', src)
        elif kind == 'R':
            ex = re.search(r'REPLAY-EXIT (-?\d+)', out)
            answers[var] = ('1' if ok else '""', src)
            if checkvar != '-':
                answers[checkvar] = ('1' if ok and ex and ex.group(1) == '0' else '""', src)
            if runvar != '-':
                answers[runvar] = (ex.group(1) if ok and ex else '"FAILED_TO_RUN"', src)
                if checkvar == '-':
                    answers[runvar + '__TRYRUN_OUTPUT'] = ('""', src)
        else:
            answers[var] = ('1' if ok else '""', src)
        added += 1
    with open(answers_path, 'w') as f:
        f.write('# CMake check answers for OpenVMS x86-64 (clang), replayed on a VMS node by\n'
                '# tools/replay.sh.  Generated: do not edit; put corrections in manual.txt.\n')
        for var in sorted(answers):
            val, src = answers[var]
            f.write('%s %s  # %s\n' % (var, val, src))
    manual = read_answers(MANUAL)
    with open(CACHE, 'w') as f:
        f.write('# Pre-cached platform check results for OpenVMS x86-64 (VSI C++/clang),\n'
                '# as cmake/os/WindowsCache.cmake does for MSVC.  CMake cannot run on VMS,\n'
                '# so a host-side cross-configure uses these instead of running the checks.\n'
                '# Generated by tools/replay_answers.py from vms/config/answers.txt (checks\n'
                '# replayed with clang on a VMS node) and vms/config/manual.txt (wins).\n\n'
                'IF(CMAKE_SYSTEM_NAME STREQUAL "OpenVMS")\n')
        for var in sorted(set(answers) | set(manual)):
            val, src = manual.get(var) or answers[var]
            tag = ' # manual' if var in manual else ''
            f.write('SET(%s %s CACHE INTERNAL "")%s\n' % (var, val, tag))
        f.write('ENDIF()\n')
    print('replay_answers: %d results merged; %d answers, %d manual -> %s' %
          (added, len(answers), len(manual), os.path.relpath(CACHE, TOP)))


if __name__ == '__main__':
    main()
